# Generated by Django 2.2.5 on 2020-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200806_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='langauge',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', 'Korean')], max_length=2, null=True),
        ),
    ]
